### ISSUE TITLE
Implementing types

### ISSUE THREAD

**Issue by HunterNN** [Codename-Recon/Codename-Recon#11]
The client should use the types placed in the "/type" folder as lookup tables. This modification will replace the current property resources, such as unit properties and terrain properties. The final structure should be located within the "client" folder, as Godot uses this as its relative starting path.

**Comment by Darkbladecr** [comment]
Let me know if I can generate the types for you in a native *.tscn file for example?
I create the template for go like this:
https://github.com/Codename-Recon/Codename-Recon/blob/master/backend/cmd/jsonImport/templates/units.tmpl
and then this gets generated to the file here:
https://github.com/Codename-Recon/Codename-Recon/blob/master/backend/pkg/models/gen_units.go

Makes it super easy if there are any changes to the json files that I only need to re-run the script and everything is updated.
