### ISSUE TITLE
B. Copter's (or any unit?) Counterattack

### ISSUE THREAD

**Issue by Zamzakun** [Codename-Recon/Codename-Recon#117]
**Describe the bug**
I tested only on the B. Copter since I was testing the animation on it, but, from what I get: if a unit has 0.1 HP, it doesn't land a counterattack (the animation doesn't play out). I assume it's because it wouldn't do damage.
However, the game should always calculate the HP as being at least 1 for ATK calculation, so I assume it's a bug, since at 1 HP, it should give 0,X dmg.

**To Reproduce**
1. Make a map with an allied Cruiser on one side. An enemy B. Copter in a 3* defense (Airport) at the center. An allied Infantry at the other side.
2. Do the attack with the Cruiser, then Infantry, with luck value, sometime it should get the B. Copter to 0.1 HP.
3. When that happens, the B. Copter with 0.1HP wouldn't shoot back.

**Expected behavior**
He should just counterattack like other units, doing X amount of damage, despite having very low HP.
Notice from the screen shot that the Infantry doesn't have the HP showing (Full HP), despite landing the attack (B. Copter at "1" HP).
**Screenshots**
![image](https://github.com/Codename-Recon/Codename-Recon/assets/113378369/8ceec9dd-9ac3-400c-9ffe-237a908e09e5)

**Desktop (please complete the following information):**
 - OS: [Windows]
 -
 -

**Smartphone (please complete the following information):**
 -

**Additional context**
Cheers.

**Comment by HunterNN** [comment]
@Zamzakun I'm unable to replicate the issue. Could you try using the latest version? https://codename-recon.github.io/Codename-Recon/

**Comment by Zamzakun** [comment]
![image](https://github.com/Codename-Recon/Codename-Recon/assets/113378369/4bf2fe1f-c739-409c-88af-a7e14450a64e)

Notice the copter/infantry below the unit selected (second row)

I had to retry 3~ times to do it right.

![image](https://github.com/Codename-Recon/Codename-Recon/assets/113378369/069744e8-c90d-4988-ac7c-63bf94f0092d)

If you look at the bottom left corner, it only "works" (or doesn't in this case, I guess) when you get it to 0.1 HP, then it doesn't even try to counter attack, leaving the HP at full HP (no number).
