### ISSUE TITLE
Missing dependency on client

### ISSUE THREAD

**Issue by Dracks** [Codename-Recon/Codename-Recon#15]
Hi, 

I just opened the project in godot, and I've got the following missing dependency:
![image](https://github.com/Codename-Recon/Codename-Recon/assets/1499165/0256aaf0-22b5-4345-b80d-848f1e623c7e)

**Comment by HunterNN** [comment]
Have you tried turning it off and on again? Jokes aside, that's an error you get the first time you open it. I'm not sure why, but I'm guessing something might be interfering with the generation of import files when Godot creates them upon starting the project for the first time. 

Just try to start it again.

**Comment by Darkbladecr** [comment]
Had the exact same bug when I first opened the project, but disappeared on second open. Might just be a bug in the way Godot imports assets on initial setup.

**Comment by HunterNN** [comment]
I really hope that doesn't disturb the continuous deployment process...

**Comment by Dracks** [comment]
It's curios, yeah, seems it doesn't happen, maybe we missed some file? I think I needed to add some of the files of the .godot to have the tests working in the pipeline, maybe something like that is missing?

**Comment by Dracks** [comment]
yes, I know, but for being able to run the gut tests in my own 3d clone of AW, I needed to have the following file, otherwise I was not able to generate it and everything was failing.
`.godot/global_script_class_cache.cfg`

**Comment by HunterNN** [comment]
I think those get generated when you run Godot once. Mabye a fix would be to run Godot first and then something like Gut.

**Comment by Dracks** [comment]
this is something that I tried... for god sake... 

I just find, that I need to run godot with -e, that is the editor. But this is discussion for another topic
