### ISSUE TITLE
Shader for coloring units and terrains does fail on web export

### ISSUE THREAD

**Issue by HunterNN** [Codename-Recon/Codename-Recon#22]
I have encountered an issue where the shader used for coloring units and terrains is not working as expected when exporting the project to a web format. I tested it in Firefox and Chromium:

![image](https://github.com/Codename-Recon/Codename-Recon/assets/1898454/bcf95c5b-6cdd-4273-aa42-1e575e816b4a)

As you can see, the units and buildings are all in their respective sprite colors.

**Comment by DigitalGhostHub** [comment]
Deleted previous export templates and redownloaded with Official Github instead of Best Available - and exported in Compatibility - now the shaders are working. Tested in Firefox and Edge and using Itch.Io with BufferArray support. (Won't catch me installing Chrome)

**Comment by HunterNN** [comment]
Based on what I can see, it seems that the problem lies in the cache generation process for the *.godot* folder. Specifically, the shader issue only occurs when this folder is missing, and it gets created using this command 
`godot --project . --headless --quit-after 1000 -e 2>/dev/null`

It seems that this step may not be necessary at all, as none of the example repositories use such a line or commit the '.godot' folder. I suspect that the --export-release flag should generate it automatically, but for some reason, it doesn't:

https://github.com/abarichello/godot-ci/issues/127

An export to the web using a normally generated '.godot' folder has no issues with color shading.

@Dracks also FYI

**Comment by HunterNN** [comment]
> Deleted previous export templates and redownloaded with Official Github instead of Best Available - and exported in Compatibility - now the shaders are working. Tested in Firefox and Edge and using Itch.Io with BufferArray support. (Won't catch me installing Chrome)

Could you please test the multiplayer feature for me if you have hosted it on Itch.io? To do this, simply click "multiplayer" and then "lobby" from the main menu. When hosting on a local computer, it appears to be unable to connect to Nakama.
![image](https://github.com/Codename-Recon/Codename-Recon/assets/1898454/6d74190a-0488-433f-9638-98320f5f38a9)

**Comment by DigitalGhostHub** [comment]
Same result on Itch.io, cannot connect to the lobby server

**Comment by HunterNN** [comment]
Ok back to topic.

It's nice that we can manually export to the web and the shader will work. But for this issue #25 we need the automatically process. So I keep this issue open.

While it's great that we can manually export to the web and have the shader working, but for this issue #25 we still need an automated solution. Therefore, I will keep this issue open for now.

I have posted a comment on the following issue on the godot-ci repository regarding this matter: https://github.com/abarichello/godot-ci/issues/127#issuecomment-1913655515

**Comment by HunterNN** [comment]
Ok back to topic.

While it's great that we can manually export to the web and have the shader working, but for this issue https://github.com/Codename-Recon/Codename-Recon/issues/25 we still need an automated solution. Therefore, I will keep this issue open for now.

I have posted a comment on the following issue on the godot-ci repository regarding this matter: https://github.com/abarichello/godot-ci/issues/127#issuecomment-1913655515

**Comment by HunterNN** [comment]
https://github.com/godotengine/godot/issues/77508

**Comment by HunterNN** [comment]
Godot 4.3 will fix this issue. It is already solved in Godot 4.3 dev 4.
