### ISSUE TITLE
Add automated deployment of web export to GitHub Pages

### ISSUE THREAD

**Issue by HunterNN** [Codename-Recon/Codename-Recon#25]
Currently, the web export of our Godot game is not automatically deployed to a GitHub page when new code is pushed. This makes it inconvenient for testers and players to access the latest version of the game.

To solve this issue, we could implement an automated build and deployment process that pushes the web export to a GitHub Pages site each time changes are merged into the main branch.

**Comment by Dracks** [comment]
more info here: 
http://angelicgarbage.com/posts/how-to-deploy-a-godot-4-game-to-github-pages/

I will try first in my fork of the project, and I will try to see if we can keep some kind of history of the last 7 builds, or similar.

**Comment by HunterNN** [comment]
There is also commented code in the export workflow, which may be helpful. If not, you can go ahead and remove it.:
https://github.com/Codename-Recon/Codename-Recon/blob/df383d65bc19214a40b0d4bae97aad8647c6cfc3/.github/workflows/client-exports.yaml#L97-L104

**Comment by Dracks** [comment]
yeah, publishing into pages usually is straight forward... The most complex part, is having the history. 

Also, one more thing, the exports that you have are only for releases/new-versions, right? I think the export to pages will make sense to be the nightly build

**Comment by HunterNN** [comment]
Currently, the files are stored as artifacts, making them resemble nightly builds for me. The release one, however, should be generated using tags. Do you think there's anything missing for nightly builds?

What do you mean by "history"? Are you referring to the change log?

**Comment by HunterNN** [comment]
Based on this https://github.com/Codename-Recon/Codename-Recon/issues/22#issuecomment-1913634510
When hosting the web export on a local computer or on Itch.io, it appears that the game is unable to connect to Nakama.

I suspect the issue may be due to the same-origin policy:
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

It appears that we can resolve this by hosting Nakama and the page under the same domain. However, I am not completely certain. @Darkbladecr Do you know if this is indeed the case?

**Comment by Dracks** [comment]
I did my fightings with cors and this stuff.. 

We can also try with cors, configuring the server that the domain of the client is a valid cors domain, it should work. 

Maybe we can do a call and take a look

**Comment by HunterNN** [comment]
FYI: https://github.com/JamesIves/github-pages-deploy-action

**Comment by Darkbladecr** [comment]
Yes it is probably a CORS restriction by Nakama, there should definitely be a way for us to configure this. On first pass through the documentation, I don't see any config/restrictions for this. Will take a closer look later.

**Comment by Dracks** [comment]
> Yes it is probably a CORS restriction by Nakama, there should definitely be a way for us to configure this. On first pass through the documentation, I don't see any config/restrictions for this. Will take a closer look later.

If I remember correctly, also different subdomain triger the cors, right? otherwise, we can use the custom domain of the github pages (I never worked with github pages before) 

I also look for cors configuration in Nakama, and I didn't find it, but I think the easy will be to put an nginx in the front, Also, with that, we can handle to put nakama in a subpath of the same public domain of the game. (Nginx serving the game, and nakama for the same domain)

**Comment by Dracks** [comment]
fixed here: https://github.com/Codename-Recon/Codename-Recon/pull/28
