### ISSUE TITLE
Automatically Add Exports to GitHub Releases on Tag

### ISSUE THREAD

**Issue by HunterNN** [Codename-Recon/Codename-Recon#27]
As part of our continuous integration and delivery pipeline for our game, we currently create artifacts for pushes and pull requests. However, we are missing the step of adding these releases to the releases page on GitHub upon pushing a tag.

**Comment by Dracks** [comment]
one thing, that I just saw, the actions/checkout v2, is old, and raises a warning in the executions, is used in the exports. I can try if I've got time to migrate in my P/R to v3 o v4 (I think in my work we have a v4) it's a small change, but it will be nice to fix it.
