### ISSUE TITLE
Incorporating gdscript toolkit linting check

### ISSUE THREAD

**Issue by HunterNN** [Codename-Recon/Codename-Recon#3]
EDIT: **Linting is throwing an exception, so we will set aside the gdscript toolkit until this issue is fixed**: https://github.com/Scony/godot-gdscript-toolkit/issues/191

As part of our development process, it is important that we maintain clean and consistent code. To help with this, we would like to implement a linter as part of our continuous integration (CI) pipeline. This will ensure that all code changes are checked for syntax errors and style issues before they are merged into the main branch.

- [ ] Enhance current code to pass linting tests
- [ ] Add linting checks as part of our CI pipeline, so that all pull requests are checked for linting errors before they can be merged

https://github.com/Scony/godot-gdscript-toolkit

The linting should allow private function calls outside of its class because it is blocking calls like `super._pressed()` (*private-method-call*)

**Comment by HunterNN** [comment]
I was experiencing issues with game.gd, map.gd, and unit.gd as gdlint reported exceptions.

**Comment by Dracks** [comment]
> I was experiencing issues with game.gd, map.gd, and unit.gd as gdlint reported exceptions.

I think we should block this issue, as the P/R until they fix the issue, in his code. Did we have a label block, or similar?

**Comment by HunterNN** [comment]
https://github.com/Scony/godot-gdscript-toolkit/issues/191
