### ISSUE TITLE
Tank has wrong "Getting Hit" animation

### ISSUE THREAD

**Issue by Zamzakun** [Codename-Recon/Codename-Recon#83]
**Describe the bug**
The tank's animation of getting hit is acting like the animation of "Idle's injured", and not of receiving damage. 

**To Reproduce**
1. Attack an Unit that doesn't die or get attacked, then observe the counterattack/attack.
2. The smoke will briefly go out of the Tank unit when it gets hit.

**Expected behavior**
It's supposed to move aside and go back to it's original position (like taking impact on hit).

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome.
 - v0.7.2

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by HunterNN** [comment]
Can you point on the sprite sheet, which row it should be? You can post images in Github just by using the clipboard (copy paste into the text area)
