### ISSUE TITLE
Shader doesn't apply some color variations (e.g. tank sprite)

### ISSUE THREAD

**Issue by Zamzakun** [Codename-Recon/Codename-Recon#84]
**Describe the bug**
The Tank's sprite don't have the highlight color it's supposed to have.

**To Reproduce**
1. See the Tank's sprite in-game.

**Expected behavior**
There was supposed to have 3 shades of the (team) color at the tank. As opposed to only 2 (which is the "default" for the infantry units)

**Screenshots**
![imagem_2024-04-20_203055387](https://github.com/Codename-Recon/Codename-Recon/assets/113378369/b8d05c30-4daf-4917-8927-bda1fe3ec4f2)
![image](https://github.com/Codename-Recon/Codename-Recon/assets/113378369/c955e7e7-51cd-47e5-8ce1-c670d93aed17)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - v0.7.2

**Smartphone (please complete the following information):**
 -

**Additional context**
-

**Comment by HunterNN** [comment]
![image](https://github.com/Codename-Recon/Codename-Recon/assets/1898454/6a63ec41-db1a-47cc-abab-eecaae4c8dbf)
