### ISSUE TITLE
The first time the client is edited in godot, it raises an error with the menu.tscn scene

### ISSUE THREAD

**Issue by Dracks** [Codename-Recon/Codename-Recon#85]
**Describe the bug**
The first time that you start editing the godot project it fails because some error on the menu.tscn

**To Reproduce**
1. Drop .godot folder
2. Run editor of the project
3. See the menu.tscn error

**Expected behavior**
It loads fine the first time

**Additional context**

I think we have some issues in the pipeline, that is related to that, with the new --import flag, we need to run it two times to fix the problems, otherwise, is complaining about some resources of the menu.tscn

**Comment by Dracks** [comment]
I was thinking, Is it possible that adding some splash screen, as the default screen, will be enough to not get this error?

**Comment by HunterNN** [comment]
Maybe. Do you want to try it out?

**Comment by HunterNN** [comment]
**Current Workaround**
1. Ensure you have a fresh copy of the game. The folder `client/.godot` should not be present.
2. Open the game with Godot.
3. Close the *missing dependencies* error window (but keep Godot open).
4. Run the game (play button -> it will crash).
5. Stop the game (square button).
6. Run it again (play button -> it will work).

Without this workaround, the error leads to missing references for the tiled file, which prevents the game from starting.

**Comment by Dracks** [comment]
I tried to add an empty scene, but still the same problem appears again. I'm not sure what is the problem. After reloading the project I had it working, if you run the game, then some assets are modified and the project is broken. 

I just ask in the forum of godot, to see if someone can enlight us.

**Comment by Dracks** [comment]
Following the recomendation of the forum, issue created:
https://github.com/godotengine/godot/issues/92262

I hope I can find some time, and make a fork to cleanup and make a minimum project
